// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hao_yang_finance_api.Data;

#nullable disable

namespace hao_yang_finance_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250720162400_AddUserAuthentication")]
    partial class AddUserAuthentication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("hao_yang_finance_api.Models.Company", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_person");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("tax_id");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("company");
                });

            modelBuilder.Entity("hao_yang_finance_api.Models.CompanyPhone", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("company_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("company_phone");
                });

            modelBuilder.Entity("hao_yang_finance_api.Models.Driver", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("driver");
                });

            modelBuilder.Entity("hao_yang_finance_api.Models.ExtraExpense", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT")
                        .HasColumnName("amount");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<decimal?>("Fee")
                        .HasColumnType("TEXT")
                        .HasColumnName("fee");

                    b.Property<string>("Item")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("item");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("WaybillId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("waybill_id");

                    b.HasKey("Id");

                    b.HasIndex("WaybillId");

                    b.ToTable("extra_expense");
                });

            modelBuilder.Entity("hao_yang_finance_api.Models.Invoice", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("company_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<bool>("ExtraExpensesIncludeTax")
                        .HasColumnType("INTEGER")
                        .HasColumnName("extra_expenses_include_tax");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_number");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("PaidAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentNote")
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("TEXT")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Tax")
                        .HasColumnType("TEXT")
                        .HasColumnName("tax");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("TEXT")
                        .HasColumnName("tax_rate");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT")
                        .HasColumnName("total");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("invoice");
                });

            modelBuilder.Entity("hao_yang_finance_api.Models.InvoiceExtraExpense", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExtraExpenseId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("extra_expense_id");

                    b.Property<string>("InvoiceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_id");

                    b.HasKey("Id");

                    b.HasIndex("ExtraExpenseId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("invoice_extra_expense");
                });

            modelBuilder.Entity("hao_yang_finance_api.Models.InvoiceWaybill", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("InvoiceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_id");

                    b.Property<string>("WaybillId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("waybill_id");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("WaybillId");

                    b.ToTable("invoice_waybill");
                });

            modelBuilder.Entity("hao_yang_finance_api.Models.LoadingLocation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FromLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("from_location");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence_order");

                    b.Property<string>("ToLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("to_location");

                    b.Property<string>("WaybillId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("waybill_id");

                    b.HasKey("Id");

                    b.HasIndex("WaybillId");

                    b.ToTable("loading_location");
                });

            modelBuilder.Entity("hao_yang_finance_api.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshTokenExpiryTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("hao_yang_finance_api.Models.Waybill", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("company_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("driver_id");

                    b.Property<decimal>("Fee")
                        .HasColumnType("TEXT")
                        .HasColumnName("fee");

                    b.Property<string>("InvoiceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_id");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("item");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("plate_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<decimal>("Tonnage")
                        .HasColumnType("TEXT")
                        .HasColumnName("tonnage");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("WaybillNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("waybill_number");

                    b.Property<string>("WorkingTimeEnd")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("working_time_end");

                    b.Property<string>("WorkingTimeStart")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("working_time_start");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DriverId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("waybill");
                });

            modelBuilder.Entity("hao_yang_finance_api.Models.CompanyPhone", b =>
                {
                    b.HasOne("hao_yang_finance_api.Models.Company", "Company")
                        .WithMany("Phones")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("hao_yang_finance_api.Models.ExtraExpense", b =>
                {
                    b.HasOne("hao_yang_finance_api.Models.Waybill", "Waybill")
                        .WithMany("ExtraExpenses")
                        .HasForeignKey("WaybillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Waybill");
                });

            modelBuilder.Entity("hao_yang_finance_api.Models.Invoice", b =>
                {
                    b.HasOne("hao_yang_finance_api.Models.Company", "Company")
                        .WithMany("Invoices")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("hao_yang_finance_api.Models.InvoiceExtraExpense", b =>
                {
                    b.HasOne("hao_yang_finance_api.Models.ExtraExpense", "ExtraExpense")
                        .WithMany()
                        .HasForeignKey("ExtraExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hao_yang_finance_api.Models.Invoice", "Invoice")
                        .WithMany("InvoiceExtraExpenses")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExtraExpense");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("hao_yang_finance_api.Models.InvoiceWaybill", b =>
                {
                    b.HasOne("hao_yang_finance_api.Models.Invoice", "Invoice")
                        .WithMany("InvoiceWaybills")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hao_yang_finance_api.Models.Waybill", "Waybill")
                        .WithMany()
                        .HasForeignKey("WaybillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Waybill");
                });

            modelBuilder.Entity("hao_yang_finance_api.Models.LoadingLocation", b =>
                {
                    b.HasOne("hao_yang_finance_api.Models.Waybill", "Waybill")
                        .WithMany("LoadingLocations")
                        .HasForeignKey("WaybillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Waybill");
                });

            modelBuilder.Entity("hao_yang_finance_api.Models.Waybill", b =>
                {
                    b.HasOne("hao_yang_finance_api.Models.Company", "Company")
                        .WithMany("Waybills")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("hao_yang_finance_api.Models.Driver", "Driver")
                        .WithMany("Waybills")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("hao_yang_finance_api.Models.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("Driver");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("hao_yang_finance_api.Models.Company", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Phones");

                    b.Navigation("Waybills");
                });

            modelBuilder.Entity("hao_yang_finance_api.Models.Driver", b =>
                {
                    b.Navigation("Waybills");
                });

            modelBuilder.Entity("hao_yang_finance_api.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceExtraExpenses");

                    b.Navigation("InvoiceWaybills");
                });

            modelBuilder.Entity("hao_yang_finance_api.Models.Waybill", b =>
                {
                    b.Navigation("ExtraExpenses");

                    b.Navigation("LoadingLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
