import { Waybill } from '../types/waybill.types';

export const SAMPLE_WAYBILLS: Waybill[] = [
	{
		id: '1',
		waybillNumber: 'WB-2025-001',
		date: '2025-07-31',
		item: 'CARGO-001',
		customerName: '經濟部中央地質調查所',
		customerId: '58c7e17d-b99d-65b1-22c7-9c6d8c68a876',
		loadingLocations: [
			{
				from: '基隆港',
				to: '台北市南港區',
			},
			{
				from: '台北市南港區',
				to: '桃園市中壢區',
			},
		],
		workingTime: {
			start: '08:00',
			end: '17:00',
		},
		fee: 15000,
		driverName: '黃天賜',
		driverId: '1',
		plateNumber: '25',
		notes: '需要特殊吊掛設備',
		extraExpenses: [
			{
				item: '油錢',
				fee: 1500,
				notes: '需要特殊吊掛設備',
			},
			{
				item: '吊掛設備',
				fee: 1000,
				notes: '需要特殊吊掛設備',
			},
		],
		isInvoiceIssued: false,
	},
	{
		id: '2',
		waybillNumber: 'WB-2025-002',
		date: '2025-07-30',
		item: 'CARGO-002',
		customerName: '永豐營造',
		loadingLocations: [
			{
				from: '新北市三重區',
				to: '台北市信義區',
			},
		],
		workingTime: {
			start: '09:00',
			end: '18:00',
		},
		fee: 12000,
		driverName: '黃天賜',
		driverId: '1',
		plateNumber: '35',
		notes: '',
		extraExpenses: [],
		isInvoiceIssued: false,
	},
	{
		id: '3',
		waybillNumber: 'WB-2025-003',
		date: '2025-07-30',
		item: 'CARGO-003',
		customerName: '國泰建設',
		loadingLocations: [
			{
				from: '桃園市大園區',
				to: '新竹科學園區',
			},
		],
		workingTime: {
			start: '07:00',
			end: '16:00',
		},
		fee: 18000,
		driverName: '陳文輝',
		driverId: '2',
		plateNumber: '50',
		notes: '需要提前到場',
		extraExpenses: [],
		isInvoiceIssued: false,
	},
	{
		id: '4',
		waybillNumber: 'WB-2025-004',
		date: '2025-07-30',
		item: 'CARGO-004',
		customerName: '遠雄集團',
		loadingLocations: [
			{
				from: '台北市內湖區',
				to: '新北市林口區',
			},
		],
		workingTime: {
			start: '10:00',
			end: '19:00',
		},
		fee: 13500,
		driverName: '陳文輝',
		driverId: '2',
		plateNumber: '40',
		notes: '特殊貨物，需要小心處理',
		extraExpenses: [],
		isInvoiceIssued: false,
	},
	{
		id: '5',
		waybillNumber: 'WB-2025-005',
		date: '2025-07-30',
		item: 'CARGO-005',
		customerName: '富邦建設',
		loadingLocations: [
			{
				from: '新北市板橋區',
				to: '台北市大安區',
			},
			{
				from: '台北市大安區',
				to: '新北市新莊區',
			},
		],
		workingTime: {
			start: '08:30',
			end: '17:30',
		},
		fee: 16000,
		driverName: '林豐基',
		driverId: '3',
		plateNumber: '30',
		notes: '需要配合工地施工時間',
		extraExpenses: [],
		isInvoiceIssued: false,
	},
	{
		id: '6',
		waybillNumber: 'WB-2025-006',
		date: '2025-07-30',
		item: 'CARGO-006',
		customerName: '經濟部中央地質調查所',
		customerId: '58c7e17d-b99d-65b1-22c7-9c6d8c68a876',
		loadingLocations: [
			{
				from: '台北港',
				to: '台北市內湖區',
			},
		],
		workingTime: {
			start: '07:30',
			end: '16:30',
		},
		fee: 14500,
		driverName: '黃天賜',
		driverId: '1',
		plateNumber: '25',
		notes: '需要保溫車',
		extraExpenses: [],
		isInvoiceIssued: false,
	},
	{
		id: '7',
		waybillNumber: 'WB-2025-007',
		date: '2025-07-30',
		item: 'CARGO-007',
		customerName: '永豐營造',
		loadingLocations: [
			{
				from: '新北市泰山區',
				to: '桃園市龜山區',
			},
			{
				from: '桃園市龜山區',
				to: '新北市林口區',
			},
		],
		workingTime: {
			start: '08:00',
			end: '17:00',
		},
		fee: 17500,
		driverName: '陳文輝',
		driverId: '2',
		plateNumber: '40',
		notes: '工地交通管制',
		extraExpenses: [],
		isInvoiceIssued: false,
	},
	{
		id: '8',
		waybillNumber: 'WB-2025-008',
		date: '2025-07-30',
		item: 'CARGO-008',
		customerName: '國泰建設',
		loadingLocations: [
			{
				from: '桃園市觀音區',
				to: '新竹市東區',
			},
		],
		workingTime: {
			start: '06:30',
			end: '15:30',
		},
		fee: 16800,
		driverName: '林豐基',
		driverId: '3',
		plateNumber: '30',
		notes: '需要吊掛證照',
		extraExpenses: [],
		isInvoiceIssued: false,
	},
	{
		id: '9',
		waybillNumber: 'WB-2025-009',
		date: '2025-07-30',
		item: 'CARGO-009',
		customerName: '遠雄集團',
		loadingLocations: [
			{
				from: '新北市五股區',
				to: '台北市松山區',
			},
		],
		workingTime: {
			start: '09:30',
			end: '18:30',
		},
		fee: 13800,
		driverName: '黃天賜',
		driverId: '1',
		plateNumber: '25',
		notes: '',
		extraExpenses: [],
		isInvoiceIssued: false,
	},
	{
		id: '10',
		waybillNumber: 'WB-2025-010',
		date: '2025-07-30',
		item: 'CARGO-010',
		customerName: '富邦建設',
		loadingLocations: [
			{
				from: '台北市萬華區',
				to: '新北市三峽區',
			},
			{
				from: '新北市三峽區',
				to: '桃園市八德區',
			},
		],
		workingTime: {
			start: '07:00',
			end: '16:00',
		},
		fee: 19000,
		driverName: '陳文輝',
		driverId: '2',
		plateNumber: '50',
		notes: '需要配合工地施工時間，請提前抵達',
		extraExpenses: [],
		isInvoiceIssued: false,
	},
	{
		id: '11',
		waybillNumber: 'WB-2025-011',
		date: '2025-07-30',
		item: 'CARGO-011',
		customerName: '台灣電力公司',
		loadingLocations: [
			{
				from: '台北市大同區',
				to: '新北市新店區',
			},
		],
		workingTime: {
			start: '08:00',
			end: '17:00',
		},
		fee: 14000,
		driverName: '林豐基',
		driverId: '3',
		plateNumber: '30',
		notes: '需要配合變電所檢修時間',
		extraExpenses: [],
		isInvoiceIssued: false,
	},
	{
		id: '12',
		waybillNumber: 'WB-2025-012',
		date: '2025-07-30',
		item: 'CARGO-012',
		customerName: '中華電信',
		loadingLocations: [
			{
				from: '新北市中和區',
				to: '台北市信義區',
			},
			{
				from: '台北市信義區',
				to: '台北市內湖區',
			},
		],
		workingTime: {
			start: '09:00',
			end: '18:00',
		},
		fee: 16500,
		driverName: '黃天賜',
		driverId: '1',
		plateNumber: '25',
		notes: '通訊設備，需要防震處理',
		extraExpenses: [],
		isInvoiceIssued: false,
	},
	{
		id: '13',
		waybillNumber: 'WB-2025-013',
		date: '2025-07-30',
		item: 'CARGO-013',
		customerName: '台灣高鐵',
		loadingLocations: [
			{
				from: '桃園市中壢區',
				to: '新竹市東區',
			},
		],
		workingTime: {
			start: '07:30',
			end: '16:30',
		},
		fee: 17800,
		driverName: '陳文輝',
		driverId: '2',
		plateNumber: '40',
		notes: '軌道零件，需要特殊固定',
		extraExpenses: [],
		isInvoiceIssued: false,
	},
	{
		id: '14',
		waybillNumber: 'WB-2025-014',
		date: '2025-07-30',
		item: 'CARGO-014',
		customerName: '台積電',
		loadingLocations: [
			{
				from: '新竹科學園區',
				to: '台中科學園區',
			},
		],
		workingTime: {
			start: '06:00',
			end: '15:00',
		},
		fee: 25000,
		driverName: '林豐基',
		driverId: '3',
		plateNumber: '30',
		notes: '精密設備，全程恆溫',
		extraExpenses: [],
		isInvoiceIssued: false,
	},
	{
		id: '15',
		waybillNumber: 'WB-2025-015',
		date: '2025-07-30',
		item: 'CARGO-015',
		customerName: '聯發科',
		loadingLocations: [
			{
				from: '新竹市東區',
				to: '台北市南港區',
			},
		],
		workingTime: {
			start: '08:30',
			end: '17:30',
		},
		fee: 15500,
		driverName: '黃天賜',
		driverId: '1',
		plateNumber: '35',
		notes: '需要無塵運輸環境',
		extraExpenses: [],
		isInvoiceIssued: false,
	},
	{
		id: '16',
		waybillNumber: 'WB-2025-016',
		date: '2025-07-30',
		item: 'CARGO-016',
		customerName: '台灣大學',
		loadingLocations: [
			{
				from: '台北市大安區',
				to: '新北市淡水區',
			},
		],
		workingTime: {
			start: '09:30',
			end: '18:30',
		},
		fee: 13000,
		driverName: '陳文輝',
		driverId: '2',
		plateNumber: '50',
		notes: '實驗室設備，小心輕放',
		extraExpenses: [],
		isInvoiceIssued: false,
	},
	{
		id: '17',
		waybillNumber: 'WB-2025-017',
		date: '2025-07-30',
		item: 'CARGO-017',
		customerName: '台北醫學大學',
		loadingLocations: [
			{
				from: '台北市信義區',
				to: '新北市三重區',
			},
			{
				from: '新北市三重區',
				to: '台北市北投區',
			},
		],
		workingTime: {
			start: '07:00',
			end: '16:00',
		},
		fee: 18500,
		driverName: '林豐基',
		driverId: '3',
		plateNumber: '30',
		notes: '醫療設備，需要避震',
		extraExpenses: [],
		isInvoiceIssued: false,
	},
	{
		id: '18',
		waybillNumber: 'WB-2025-018',
		date: '2025-07-30',
		item: 'CARGO-018',
		customerName: '台灣中油',
		loadingLocations: [
			{
				from: '桃園市觀音區',
				to: '新北市林口區',
			},
		],
		workingTime: {
			start: '06:30',
			end: '15:30',
		},
		fee: 16000,
		driverName: '黃天賜',
		driverId: '1',
		plateNumber: '25',
		notes: '危險物品，需要特殊許可',
		extraExpenses: [],
		isInvoiceIssued: false,
	},
	{
		id: '19',
		waybillNumber: 'WB-2025-019',
		date: '2025-07-30',
		item: 'CARGO-019',
		customerName: '台灣水泥',
		loadingLocations: [
			{
				from: '新北市樹林區',
				to: '桃園市龜山區',
			},
		],
		workingTime: {
			start: '08:00',
			end: '17:00',
		},
		fee: 14500,
		driverName: '陳文輝',
		driverId: '2',
		plateNumber: '40',
		notes: '重型建材，需要大型吊掛',
		extraExpenses: [],
		isInvoiceIssued: false,
	},
	{
		id: '20',
		waybillNumber: 'WB-2025-020',
		date: '2025-07-30',
		item: 'CARGO-020',
		customerName: '台灣玻璃',
		loadingLocations: [
			{
				from: '新北市土城區',
				to: '台北市松山區',
			},
			{
				from: '台北市松山區',
				to: '新北市汐止區',
			},
		],
		workingTime: {
			start: '09:00',
			end: '18:00',
		},
		fee: 17000,
		driverName: '林豐基',
		driverId: '3',
		plateNumber: '30',
		notes: '易碎物品，需要特殊包裝',
		extraExpenses: [],
		isInvoiceIssued: false,
	},
];
